In [1]:
import numpy as np

In [23]:
countsForProperties = [2,3,4]
numObjects = 10

numProperty =len(countsForProperties)
ground = np.zeros((numObjects,numProperty), dtype=np.int)

for i in range(numProperty):
    ground[:,i] = np.random.randint(low=0, high=countsForProperties[i], size=numObjects)
    
ground

array([[1, 1, 0],
       [0, 2, 3],
       [0, 0, 2],
       [0, 1, 2],
       [1, 0, 3],
       [1, 1, 1],
       [1, 1, 3],
       [1, 2, 3],
       [1, 1, 2],
       [0, 2, 0]])

In [53]:
def appearance(array, countsForProperties=None, permList=None):
    numObjects, numProperties = array.shape
    if countsForProperties == None:
        countsForProperties = [len(set(array[:,i])) for i in range(numProperties)]
    if permList == None:
        permList = [np.random.permutation(i) for i in countsForProperties]
        
    permArray = np.zeros_like(array)
    for i in range(numProperties):
        thisPerm = permList[i]
        for j in range(numObjects):
            permArray[j,i] = thisPerm[array[j,i]]
            
    return permArray,permList
        

In [54]:
print(ground)
permArray, permList = appearance(ground)
print(permArray)

[[1 1 0]
 [0 2 3]
 [0 0 2]
 [0 1 2]
 [1 0 3]
 [1 1 1]
 [1 1 3]
 [1 2 3]
 [1 1 2]
 [0 2 0]]
[[1 1 3]
 [0 2 1]
 [0 0 2]
 [0 1 2]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [1 2 1]
 [1 1 2]
 [0 2 3]]
